POST http://localhost:3000/departamento
Content-Type: application/json

{
  "nome": "Refrigerado",
  "descricao": "Categoria para refrigerados em geral"
}

###
GET http://localhost:3000/departamento

###
GET http://localhost:3000/departamento/resumo


###
GET http://localhost:3000/departamento/74

###